{% set version = "1.18.2" %}

package:
  name: typos
  version: {{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v{{ version }}.tar.gz
  sha256: 0d8b42c9651b2b30a7a7f504f681ef52b61c5d5392f42d131da249ef52c8ccbe

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - typos --help

about:
  home: https://github.com/crate-ci/typos
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Source code spell checker
  dev_url: https://github.com/crate-ci/typos

extra:
  recipe-maintainers:
    - DamianBarabonkovQC
    - pavelzw
